### ISSUE TITLE
Don't expose global  ResizeObserver

### ISSUE THREAD

**Issue by yesmeck** [que-etc/resize-observer-polyfill#44]
We've received bug reports that TypeScript complaints `Cannot find name 'ResizeObserver'.`[#13405](https://github.com/ant-design/ant-design/issues/13405). Here is the [code](https://github.com/ant-design/ant-design/blob/fb07e3f3c441811d3a683f36ad1e8fd87a717cba/components/input/TextArea.tsx#L46) shows how we use `ResizeObserver`.

I found that TypeScript removes the `import ResizeObserver from 'resize-observer-polyfill'`  statement when generating declaration file. Here is the generated declaration file https://unpkg.com/antd@3.11.0/lib/input/TextArea.d.ts

The reason I guess is `ResizeObserver` was exposed as a global interface, not sure if it's a bug of TypeScript. But as https://github.com/que-etc/resize-observer-polyfill/issues/37#issuecomment-401352669 said, this library is actually a ponyfill, so there is no need to expose ResizeObserver as global right?

**Comment by weswigham** [comment]
Alternatively, include the interface in the export~

**Comment by que-etc** [comment]
Fixed in [v1.5.1](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.5.1).

**Comment by ndbroadbent** [comment]
Hello, I am still getting this type error with version `1.5.1`. See: https://github.com/ant-design/ant-design/issues/13405#issuecomment-447288908

Could this be a problem with my `tsconfig.json`?

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "es5",
      "es2015.promise",
      "es2015.symbol",
      "es2015.collection",
      "esnext.array"
    ],
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": ["src"]
}
```

EDIT: Sorry, false alarm. This was fixed when I upgraded to `antd` version `3.11.2`
